export const environment = {
  production: true,
  apiUrl: 'https://coedigitaldashboard.skytap-tss.vodafone.com/api/',
  applicationTypeAPIUrl: 'ApplicationTypes',
  attachmentTypeAPIUrl: 'AttachmentTypes',
  businessDomainAPIUrl: 'BusinessDomains',
  customerAPIUrl: 'Customers',
  fiscalYearAPIUrl: 'FiscalYears',
  productivityAnalystAPIUrl: 'ProductivityAnalysts',
  RPATypeAPIUrl: 'RpaTypes',
  TargetSystemAPIUrl: 'TargetSystems',
  TechnologyAPIUrl: 'Technologies',
  TransactionTypeAPIUrl: 'TransactionTypes',
  TransactionTypeValueAPIUrl: 'TransactionTypeValues',
  projectAPIUrl: 'Projects',
  processesAPIURL: 'processes',
  versionsAPIUrl: 'Versions',
  monthsAPIUrl: 'Months',
  versiontypes: 'VersionTypes',
  userstoriesAPIUrl: 'UserStories',
  attachmentsAPIUrl: 'https://coedigitaldashboard.skytap-tss.vodafone.com/api/Attachments',
  attachmentAPIUrlTitle: 'Attachments',
  baselinesAPIUrl: 'Baselines',
  auth: {
    clientID: 'G63vMvSEF0ACMGUTJq1xZUZ2rSS7TS8c',
    domain: 'dev-jy4o22j5.eu.auth0.com',
    audience: 'https://coedigitaldashboard.skytap-tss.vodafone.com/',
    redirect: 'https://digitalcoedashboard.skytap-tss.vodafone.com/',
    scope: ''
  }
};
