export const environment = {
  production: true,
  apiUrl: 'https://localhost:44367/api/',
  applicationTypeAPIUrl: 'ApplicationTypes',
  attachmentTypeAPIUrl: 'AttachmentTypes',
  businessDomainAPIUrl: 'BusinessDomains',
  customerAPIUrl: 'Customers',
  fiscalYearAPIUrl: 'FiscalYears',
  productivityAnalystAPIUrl: 'ProductivityAnalysts',
  RPATypeAPIUrl: 'RpaTypes',
  TargetSystemAPIUrl: 'TargetSystems',
  TechnologyAPIUrl: 'Technologies',
  TransactionTypeAPIUrl: 'TransactionTypes',
  TransactionTypeValueAPIUrl: 'TransactionTypeValues',
  projectAPIUrl: 'Projects',
  processesAPIURL: 'processes',
  versionsAPIUrl: 'Versions',
  monthsAPIUrl: 'Months',
  versiontypes: 'versionTypes',
  userstoriesAPIUrl: 'UserStories',
  attachmentsAPIUrl: 'https://localhost:44367/api/Attachments',
  attachmentAPIUrlTitle: 'Attachments',
  auth: {
    clientID: 'du24sh2ssXFO5uNH6fAow1ylSPQAzmKD',
    domain: 'dev-jy4o22j5.eu.auth0.com',
    audience: 'http://localhost:4200/',
    redirect: 'http://localhost:4200/',
    scope: ''
  }
};
